### ISSUE TITLE
3.6.0 causing issues in live preview

### ISSUE THREAD

**Issue by strandofgenius** [angell-co/Spoon#101]
I have a set of matrix blocks for different content types. Before upgrading to 3.6.0 I added a new field to one of the blocks in the core Craft field editor and then realized I couldn't edit the blocks in Spoon settings until I upgraded. Since upgrading, I added the new field to the matrix block, and now when I want to add additional blocks to a page only the type that I added the field to displays and the rest disappear from the preview. It's not actually deleting any blocks. I can save the entry and have the content display on the frontend, just not in preview.

**Comment by strandofgenius** [comment]
Turns out it might be related to this : https://github.com/craftcms/cms/issues/6902

**Comment by joshangell** [comment]
Phew! Thanks for letting me know @strandofgenius 👍
