### ISSUE TITLE
Add support for the "Typed Link Field" plugin

### ISSUE THREAD

**Issue by kisonay** [angell-co/Spoon#11]
Not really sure what the cause of this is but when I add multiple blocks things start to get a little wonky.

<img width="794" alt="screen shot 2018-07-21 at 9 00 10 am" src="https://user-images.githubusercontent.com/1854267/43036306-99d6992e-8cc4-11e8-88e2-0369dc00f2d5.png">

<img width="791" alt="screen shot 2018-07-21 at 9 00 32 am" src="https://user-images.githubusercontent.com/1854267/43036304-972d913c-8cc4-11e8-9205-019527923dd0.png">

If I collapse all blocks, the add block bar goes to the correct position again. If I move blocks around, the big space below the first field will fix and appear on a different block. Always appears to be an issue that starts with the third block.

**Comment by joshangell** [comment]
Hi @kisonay, thanks for the bug report. Please could you come back to me with your browser version, Craft version, Spoon version and any other plugins you have installed.

Thanks!

**Comment by kisonay** [comment]
It might be related to the custom field type "link entry" It's the latest version of Craft3 and Chrome. I'll try to get you the list of information requested as soon as possible.

**Comment by joshangell** [comment]
Thanks, you could try disabling that field types’s plugin and see if the issue goes away.

**Comment by kisonay** [comment]
I would say that is the culprit. Everything appears normal with it disabled.

**Comment by joshangell** [comment]
Cool, thank you for confirming that. Is this a publicly available plugin?

**Comment by kisonay** [comment]
Yes Sir...

<img width="318" alt="screen shot 2018-07-23 at 7 22 26 am 1" src="https://user-images.githubusercontent.com/1854267/43076241-33c7237a-8e49-11e8-9e01-7b584e3e7076.png">

**Comment by joshangell** [comment]
Ah cool, I will see if we can support it in some way :)

**Comment by joshangell** [comment]
Yeah I can’t seem to reproduce this either ... just installed the plugin and had a play and it seems fine. I’ll close for now!

**Comment by kisonay** [comment]
Thank you for taking the time to look into it. Perhaps things just got a bit stuck and the disable/enable sorted it out.
