### ISSUE TITLE
[4.0.0-beta][bug] error on plugin settings page when Super Table installed

### ISSUE THREAD

**Issue by tomdavies** [angell-co/Spoon#119]
Howdy folks 👋. When attempting to navigate to the plugin's settings page in the CP with Super Table installed, an error is thrown:

```
Class "doublesecretagency\spoon\verbb\supertable\services\SuperTableService" not found
```
This is just due to the [service name having changed in the C4 version of that plugin](https://github.com/verbb/super-table/tree/craft-4/src/services). Changing 

```php
$superTableService = new verbb\supertable\services\SuperTableService();
```

to
```php
$superTableService = new \verbb\supertable\services\Service();
```

fixes the error

FWIW I am running:
- Craft CMS 4.2.5.2
- Spoon 4.0.0.beta-1
- Super Table 3.0.1

**Comment by lindseydiloreto** [comment]
Thanks for reporting! This change has been included in **Spoon v4.0.0** (post-beta).
