### ISSUE TITLE
ImageOptimize plugin field settings do not display when Spoon is enabled

### ISSUE THREAD

**Issue by BenParizek** [angell-co/Spoon#15]
Screenshot: http://share.barrelstrength.co/10390c1z1N2D
Related issue: https://github.com/nystudio107/craft-imageoptimize/issues/94

The ImageOptimize plugin uses matrix block classes in how it styles its settings pages:
https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/templates/_components/fields/OptimizedImages_settings.twig#L69

It seems the styles Spoon adds to the CP may conflict with these in some way. I haven't dug too deep so not sure if the primary issue is in Spoon or in ImageOptimize. Hopefully you folks can coordinate and find a common ground.

**Comment by joshangell** [comment]
Thanks Ben, I'll take a look!

**Comment by khalwat** [comment]
Yep, I'm happy to add whatever wrapper class you need me to add @joshangell -- just lmk where/how to add it!

**Comment by joshangell** [comment]
@BenParizek Fixed in this PR here: https://github.com/nystudio107/craft-imageoptimize/pull/96

**Comment by joshangell** [comment]
Fixed in the confetti release: https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.38
