### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by H-i-red** [angell-co/Spoon#17]
A lot of layout issues (see screenshots).

Mac
Firefox 61.0.2
Craft Solo 3.0.21
PHP 7.2.1

![4](https://user-images.githubusercontent.com/19476159/44619055-fd139780-a880-11e8-8e51-ca07a2f556fb.png)
![1](https://user-images.githubusercontent.com/19476159/44619071-19afcf80-a881-11e8-9d4f-4e5bb93d4576.png)
![5](https://user-images.githubusercontent.com/19476159/44619050-ec632180-a880-11e8-8ef0-52f66b498b00.png)

**Comment by joshangell** [comment]
Interesting, thanks for this. I'll take a look when I'm back from paternity
leave in another week or so.

**Comment by H-i-red** [comment]
1. `.spoon-fields` only get styled by `opacity: 0` and taking up space, when it should be set to `display:none` or `height: 0px`.
2. `.spoon-tabs` are still clickable in collapsed mode, same here `opacity:0`.

**Comment by H-i-red** [comment]
`.titlebar > .preview` data gets lost upon expanding the matrixblock. When I collapse the block and save the page the preview data is back. But as soon as I expand it again its lost..

**Comment by H-i-red** [comment]
Does not remember `collapsed / expanded` state upon **first** save ! Collaps it again and save a **second** time then it _remebers_ ...

**Comment by joshangell** [comment]
OK, so there is obviously something unusual going on.

Could you please try in an alternate browser such as Chrome for me?

Also, please could you send me a database to josh@angell.io so I can try
and reproduce your issue.

My gut instinct is that it could be something to do with another plugin.

**Comment by H-i-red** [comment]
I went for another solution / plugin, thanks for help.

**Comment by joshangell** [comment]
Cool, sorry it didn’t work for you, I can’t reproduce any of these issues though so it would be helpful if you could give me a list of plugins you had installed at some point, then I can work out what was causing the conflict.

**Comment by dennisfrank** [comment]
I have the same problem. When a matrix block is collapsed, there are often layout issues with the following block. 

This fixed it for me: 

```css
.matrixblock-spooned {
    overflow: hidden;
}
```

**Comment by joshangell** [comment]
@dennisfrank interesting, could you please humour me and send a db backup and composer.json over to josh@angell.io? I really want to reproduce this one so I can debug it!
