### ISSUE TITLE
Excluding required field from field layout prevents saving of entry

### ISSUE THREAD

**Issue by jamielaughton** [angell-co/Spoon#18]
I'm using a spooned matrix component a couple of different ways, depending on which fields I include through 'edit field layout'.

I have a field which when included, I want to be required. My issue is that when I do not include the field I cannot save the entry. It looks like Craft is registering the required field, even if it is not included and preventing save.

**Comment by joshangell** [comment]
Hi Jamie,

This is to be expected in one sense, as all Spoon does is sit on top of a
normal Matrix field.

So if you require a field in the Matrix configuration it will always be
required, even if you can't see it.

I'm not sure if there is a way around it whilst keeping the core plugin
premise of using only the core Matrix.

I'm back at work from paternity leave next week so I'll try and take a look
then and see if it's possible in some way 😊

**Comment by jamielaughton** [comment]
That makes sense, and I understand you wouldn't want to add functionality that would break pages if Spoon was to be uninstalled.   

It's easy to work around by adding clear field instructions etc, so it's not a biggie.

Once you're back off paternity I should be just starting mine 😊 Congrats on the new addition!

**Comment by joshangell** [comment]
Ah thanks, and congrats to you too!

I just realised that there is server side validation too, so it would never be possible with just hi-jacking the front-end, which means its probably not a good idea to try and sort so I’ll close this for now.
