### ISSUE TITLE
Too much whitespace in dropdowns

### ISSUE THREAD

**Issue by joshangell** [angell-co/Spoon#2]
From https://github.com/angell-co/Pimp-My-Matrix/issues/25 by @bossanova808

---

I still think the whitespace is a lot too much though, personally. Or possibly some sort of nested organisation would help too...once you have a bunch of types, the drop down is still very large

![](https://user-images.githubusercontent.com/731309/42249593-7fde4fd8-7f6f-11e8-9ef7-80d217d10737.png)

**Comment by joshangell** [comment]
Thanks for this Jeremy, I will see if we can tighten up the list or perhaps use some kind of toggle and collapse all the groups - for now I’m just using the native button list styles.

**Comment by bossanova808** [comment]
Hey Josh - well I certainly  like it.  I guess you might want other's opinions of course!  And I guess it would be configurable?    

That would certainly help us, at least - we have a pretty full on page builder going on (as you can see!), and I think this would make the editing process noticeably better

**Comment by joshangell** [comment]
Yeah I think it's useful, having played with it a bit now. I'll add it as a configurable thing which you can turn on per Matrix field from a config file, does that sound good?

**Comment by bossanova808** [comment]
Sounds awesome!

**Comment by joshangell** [comment]
OK, this is done in 8a89fd88a1fac5988912ebe76078b7cab046a866
