### ISSUE TITLE
Cannot drag field onto group if group is offscreen

### ISSUE THREAD

**Issue by johnwbaxter** [angell-co/Spoon#23]
Steps to reproduce:

Create a long list of fields and create a Spoon field group.
Scroll down in modal until group is out of view.
Drag field up to put into group.
Content doesn't scroll up so you never see group.

Tested in Version 3.2.0 of Spoon.

**Comment by joshangell** [comment]
Workaround is to use the up/down arrow keys to move the modal content pane for now.

**Comment by joshangell** [comment]
Closing as new field layout engine in Craft 3.5 is in use and you can just use the search to find the field, which should avoid this problem.
