### ISSUE TITLE
Support Project Config

### ISSUE THREAD

**Issue by joshangell** [angell-co/Spoon#24]
See here: https://craftcms.com/support/craft-3-1-dev-preview-notes#project-config

https://github.com/craftcms/cms/blob/3.1/docs/extend/project-config.md

https://craftcms.com/guides/updating-plugins-for-craft-3-1

**Comment by michaelroper** [comment]
Hey Josh! Any idea when this might land? Would be super-helpful to have Spoon config changes synced by project config...

**Comment by javangriff** [comment]
Hi @joshangell, any update on when project config support might be implemented? It would be super handy.

**Comment by dennisfrank** [comment]
It really would be super awesome! Spoon is the only plugin I need to update on the live server after every config change.

**Comment by joshangell** [comment]
Argh I’m sorry everyone - I will get to it I promise, currently really under the gun with a non-sleeping child so most weeks just doing the bare minimum to keep things afloat. Its been a long time I appreciate, but I will get there - please do bear with me :)

**Comment by vSanjo** [comment]
Appreciate the work, @joshangell. 

Can't wait to see this land.

**Comment by engram-design** [comment]
@joshangell Just going to be annoying and upvote this too 😄 let me know if we need to chat about it and can look at a PR if you're flat-out?

**Comment by joshangell** [comment]
@engram-design Haha no worries - I’m finally getting around to other work at long last, its been a while! Thanks for the offer of help, I’ll let you know in a few days if I think I’ll need a hand, just getting my head back into it right now.

**Comment by engram-design** [comment]
@joshangell No problem, just was keen to see where you were at with it - no point in starting something if you're already (or about to) dive in

**Comment by dennisfrank** [comment]
Any news on this one?

**Comment by joshangell** [comment]
@dennisfrank thanks for the prod ... I’ve been swamped but put aside a few things to focus on getting this done, it’s been bugging me for long enough now 😂

**Comment by joshangell** [comment]
Right - this should be done now, please do let me know if anything breaks! And thanks for your patience ...

**Comment by dennisfrank** [comment]
@joshangell Thank you so much! I'll test it next week!
