### ISSUE TITLE
Detect errors preventing save, highlight applicable tab

### ISSUE THREAD

**Issue by chasegiunta** [angell-co/Spoon#27]
If there's any tabs that contain required fields, and those fields are preventing save, there's no indicator on which tab, in which field, is preventing the save without going through every tab on Spoon field.

Would be great if Spoon could figure out which tabs need attention and highlight that tab text red, just as regular entry tabs do.

**Comment by joshangell** [comment]
Good spot! Thanks Chase.

**Comment by joshangell** [comment]
Looks like this

![](https://joshangell.s3.amazonaws.com/share/1._joshJoshs-MacBook-Pro_Developmentcms_zsh_2018-10-12_16-03-38.png)

**Comment by chasegiunta** [comment]
Looks great man!
