### ISSUE TITLE
Entry types falling back to wrong configuration

### ISSUE THREAD

**Issue by elivz** [angell-co/Spoon#28]
I have a single "content" Matrix field with a bunch of different block types that I use for many of the entry types throughout my site. I set up a global layout that most of the types use, but also customized it for several entry types (to limit the blocks that are available). The issue comes for entry types that have no explicit layout. Instead of falling back to the global layout, they appear to be using the layout of the entry type with the lowest ID. So all of my entry types with no specific layout are using the layout from the homepage (Entry Type #1). If I delete the configuration for the homepage, it – and the rest – start using the layout from Entry Type #2.

I have the most recent version of both Craft & Spoon. Let me know if you need more information to reproduce or want access to my staging site.

**Comment by joshangell** [comment]
OK this is actually released now with a bunch of other stuff, so just update instead :)
