### ISSUE TITLE
[Question] Release Date and Cost?

### ISSUE THREAD

**Issue by kisonay** [angell-co/Spoon#3]
I was just cuious if you had any more information about this? I have been egarly waiting a simliar plugin to come to Craft3. I have a site that is waiting to go to production and would love to use your plugin in its place.

**Comment by joshangell** [comment]
Release date is probably this week, just need to submit it to the store and wait for it to get approved.

Cost, likely $59 with a lower annual updates fee.

If you need to you can just use it on your site now, if it causes issues you can always disable it and let the core Matrix go back to its normal self :)

**Comment by kisonay** [comment]
Would love to but having problems with getting composer to load it. added the repository to composer.json:

`"repositories": [
    {
      "url": "https://github.com/angell-co/Spoon",
      "type": "git"
    }
  ],`

but get the following error when running `composer install angellco/spoon`

```
[InvalidArgumentException]              
  Could not find package angellco/spoon.  
                                          
  Did you mean this?                      
      angellco/spoon  
```

**Comment by joshangell** [comment]
Ah, undo all of that and just run `composer require angellco/spoon:dev-master`, that will put you on the master branch. When I release it you will need to `composer remove angellco/spoon` and then `composer require angellco/spoon` to get back onto stable.
