### ISSUE TITLE
Integration with Solspace Calendar

### ISSUE THREAD

**Issue by jamielaughton** [angell-co/Spoon#36]
I have a 'Content Builder' Matrix field in which I'm using Spoon to build all content around my site. 

My events are using Solspace Calendar, within the calendar you can design your field layout the same as in crafts sections. 

There is no option to 'Group block types' when I click the cog on the Matrix field. Is there something I am missing to get Spoon to work within the calendar or do you not support it?

Cheers

**Comment by jamielaughton** [comment]
Bit of extra info on this.

With the spoon plugin enabled I can't access all of the fields within the matrix block in Calendar, it just displays the first one. After I disable the plugin all the fields become visible again.

**Comment by joshangell** [comment]
Hi Jamie,

Thanks for this - right now Spoon doesn't support Solspace Calendar but it
shouldn't be too hard to sort.

I will have a look next week for you when I'm back at work.

Thanks!

Josh

**Comment by joshangell** [comment]
Just a quick update @jamielaughton - unfortunately I’ve been a bit snowed under, it’ll likely be after I get back from holiday in a week or so now that I get chance to look at this.

**Comment by jamielaughton** [comment]
Hi Josh,

I've been away from this project for a few months. After updating everything I'm still not seeing Spoon functionality in Calendar. Is this integration possible?

Cheers,
Jamie

**Comment by joshangell** [comment]
Hi Jamie,

I've been caught up in a few other things but I'll try and get to it soon
for you.

Josh

**Comment by joshangell** [comment]
Hey @jamielaughton - so good news, the latest version of Spoon included a big JS refactoring which has made the Global block type configurations you have work anywhere, including in Calendar.

I’m working on adding specific calendar contexts now, which will mean you can have configurations that are specific to each calendar.

**Comment by joshangell** [comment]
OK, this commit adds this feature: 6a9a9d47bca8292050396910822db5ba116a7677

**Comment by jamielaughton** [comment]
Perfect, thanks mate. That's working great
