### ISSUE TITLE
Can't install on Beta 5 of Craft 3.1

### ISSUE THREAD

**Issue by andersonlyle** [angell-co/Spoon#40]
Spoon will install, but won't activate in Beta 5 of 3.1.

**Comment by joshangell** [comment]
Thanks for this - will look into it when I'm back at my desk in a week or so.

**Comment by joshangell** [comment]
Hey @andersonlyle thanks for this - could you install from the `feature/3.1-beta` branch and see if that sorts it for you?

**Comment by joshangell** [comment]
Try this: `composer require angellco/spoon:dev-feature/3.1-beta`

**Comment by andersonlyle** [comment]
Thanks Josh - that worked fine.  Still having the same problem as before -
it shows as Not installed in the plugin settings.  I can’t activate it from
there.

Regards,
Lyle

Lyle Anderson
Partner
Get Reel Productions, LLC Tel: 646-240-9300
Email: lyle@lcanderson.com
Website:http://www.getreelproductions.org
Address: 400 King Street, Chappaqua, NY 10514
<http://facebook.com/getreelproductionsllc/> <http://twitter.com/GetReelNY>
<http://vimeo.com/getreel>


On January 10, 2019 at 10:34:18 AM, Josh Angell (notifications@github.com)
wrote:

composer require angellco/spoon:dev-feature/3.1-beta

**Comment by joshangell** [comment]
Hmm OK - will keep digging!

**Comment by joshangell** [comment]
More fixes in:
114a346e1c59f6fd98a5336c4ce89202793186d8
a922c3664acebda9d4b23f29c9351acea406d8cd

**Comment by joshangell** [comment]
@andersonlyle Right - I could reproduce this now - please could you have another go? Thanks!

**Comment by andersonlyle** [comment]
This version installed - not let me try it.

Regards,
Lyle

Lyle Anderson
Partner
Get Reel Productions, LLC Tel: 646-240-9300
Email: lyle@lcanderson.com
Website:http://www.getreelproductions.org
Address: 400 King Street, Chappaqua, NY 10514
<http://facebook.com/getreelproductionsllc/> <http://twitter.com/GetReelNY>
<http://vimeo.com/getreel>


On January 10, 2019 at 10:53:09 AM, Josh Angell (notifications@github.com)
wrote:

@andersonlyle <https://github.com/andersonlyle> Right - I could reproduce
this now - please could you have another go? Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/angell-co/Spoon/issues/40#issuecomment-453145742>, or mute
the thread

**Comment by andersonlyle** [comment]
It looks like it’s working.  Was able to group fields and use the groupings
on entries.  Yeah!

Regards,
Lyle

Lyle Anderson
Partner
Get Reel Productions, LLC Tel: 646-240-9300
Email: lyle@lcanderson.com
Website:http://www.getreelproductions.org
Address: 400 King Street, Chappaqua, NY 10514
<http://facebook.com/getreelproductionsllc/> <http://twitter.com/GetReelNY>
<http://vimeo.com/getreel>


On January 10, 2019 at 10:53:09 AM, Josh Angell (notifications@github.com)
wrote:

@andersonlyle <https://github.com/andersonlyle> Right - I could reproduce
this now - please could you have another go? Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/angell-co/Spoon/issues/40#issuecomment-453145742>, or mute
the thread

**Comment by joshangell** [comment]
Excellent! Good stuff. Give me a shout if anything else breaks :)
