### ISSUE TITLE
Folded Blocks Problem

### ISSUE THREAD

**Issue by davidhellmann** [angell-co/Spoon#41]
News Version (Craft / Spoon)
When I fold some blocks there is a problem with the block below the folded one. When I save the entry all its fine

![image](https://user-images.githubusercontent.com/764292/50631199-c4c54980-0f43-11e9-9daa-54e7c009ff1f.png)

**Comment by joshangell** [comment]
Thanks for this David, I'll have a look for you next week when I'm back at work :)

When you save and Entry the content should always be OK because Spoon is just a layer on top of Matrix, it doesn't modify the content at all.

**Comment by davidhellmann** [comment]
Sounds good. Yeah, looks like an JS issue.

**Comment by joshangell** [comment]
Hi @davidhellmann - I can’t seem to reproduce this ... is it limited to the "Shop Teaser" block seen in your screen shot?

**Comment by davidhellmann** [comment]
It's not on every Panel. But I see no pattern for this. 
It's a bit strange. Maybe an Craft Update makes problems or another plugin. Not sure at the moment. 
But we've it in a other project too the problem

![image](https://user-images.githubusercontent.com/764292/51026695-675a7980-158f-11e9-814e-ffff6a36f32e.png)

**Comment by joshangell** [comment]
Hey @davidhellmann - I really can’t reproduce this error at the moment, do you have any more information that I could use to debug it? Even better would be if you can email a db backup and composer.json for your project to josh@angell.io

**Comment by joshangell** [comment]
Ok this is probably solved by the latest release (3.3.0) which involves a refactor of how the JavaScript is attached to the Matrix field. Do let me know if you keep seeing this issue.
