### ISSUE TITLE
PHP notice after updating to Craft 3.1.6.1

### ISSUE THREAD

**Issue by nilsenpaul** [angell-co/Spoon#45]
I get a PHP notice after upgrading to Craft 3.1.6.1, but don't really know where to start debugging. The problem originates when getting the blockTypes (see screenshot). Please tell me what information you need to get this solved :)

![schermafbeelding 2019-01-30 om 16 15 42](https://user-images.githubusercontent.com/6794819/51991046-8a9b8900-24aa-11e9-82be-f7e823db4775.png)

**Comment by joshangell** [comment]
Aha thanks for catching that, I'll push a fix tomorrow sometime hopefully!

**Comment by joshangell** [comment]
Hi @nilsenpaul could you give me a bit more background about your setup? If possible could you send your composer.json and a database backup to josh@angell.io to help me debug this.

**Comment by phoob** [comment]
Maybe related to this? https://github.com/angell-co/Spoon/pull/46

**Comment by joshangell** [comment]
Merged #46 in and hoping it fixes this too.
