### ISSUE TITLE
Basic Neo Support

### ISSUE THREAD

**Issue by kylecotter** [angell-co/Spoon#47]
Hi!

From an author experience standpoint, it makes sense for us to have a matrix field within a [Neo](https://github.com/spicywebau/craft-neo) field.

It doesn't appear Spoon works when nested like that. Is that a possibility? Similar to how Super Table support works?

Thanks!

**Comment by joshangell** [comment]
Probably not going to do this ... if anyone wants to open a PR then I’ll happily review it, I’m keen to not overcomplicate things.
