### ISSUE TITLE
undefined label in preview mode

### ISSUE THREAD

**Issue by kisonay** [angell-co/Spoon#5]
When in live preview mode, the matrix dropdown is being displayed as "undefined"
<img width="184" alt="screen shot 2018-07-05 at 8 22 16 pm" src="https://user-images.githubusercontent.com/1854267/42355165-3921d498-8091-11e8-8789-1ef54735bc2e.png">

**Comment by joshangell** [comment]
Hi @kisonay, I’m not sure how you are seeing this ... are you on the latest `dev-develop` tag?

**Comment by kisonay** [comment]
actually useing `dev-master` let me try `dev-develop`

**Comment by kisonay** [comment]
Yes, i still see this in `dev-develop` what can I do to provide more info?

**Comment by joshangell** [comment]
Could you paste a larger screenshot? And the Craft version you are on.

**Comment by kisonay** [comment]
Craft edition & version | Craft Pro 3.0.14

Looks to be specifically related to the width of the live preview editor column.

<img width="1386" alt="screen shot 2018-07-06 at 9 34 45 am" src="https://user-images.githubusercontent.com/1854267/42384625-2547f12c-8100-11e8-891a-1bb8e2d0eb60.png">

Narrower column:

<img width="1388" alt="screen shot 2018-07-06 at 9 34 56 am" src="https://user-images.githubusercontent.com/1854267/42384646-2eeff134-8100-11e8-804c-44b2585b17b2.png">

Can I also recomend a better UI for tabs in this mode? They bunch all up and you can't read them. Can we have a dropdown simliar to the gear icon and just show the currently active tab?

<img width="1385" alt="screen shot 2018-07-06 at 9 35 19 am" src="https://user-images.githubusercontent.com/1854267/42384691-4b78da6e-8100-11e8-9c97-b5a91ba60fd6.png">

<img width="217" alt="screen shot 2018-07-06 at 9 38 45 am" src="https://user-images.githubusercontent.com/1854267/42384745-6a00b5ba-8100-11e8-8a77-9a2e4b8ecb8b.png">

**Comment by joshangell** [comment]
Aaah got it, and yep - I noticed the tabs issue yesterday, will log it :)

**Comment by joshangell** [comment]
OK, you can see the fixed version now in the tag `dev-release/3.0.0`

**Comment by kisonay** [comment]
requirement of Craft 3.0.15 which doesnt seem to be availble yet.

**Comment by joshangell** [comment]
Ah, sorry, thats because I’m waiting for a change in the core to be released ... I’ve temporarily disabled that now ...

**Comment by kisonay** [comment]
Add block label has been fixed (no longer shows as undefined.) Do you want me to open a seporate issue for the field tabs?

**Comment by joshangell** [comment]
Thanks for confirming that - I have already opened a new issue for the tabs here: https://github.com/angell-co/Spoon/issues/6

Thanks for your help!
