### ISSUE TITLE
Duplicate fields on field settings page

### ISSUE THREAD

**Issue by nilsenpaul** [angell-co/Spoon#56]
After upgrading Craft, all fields on the field settings page are shown twice. After a bit of debugging, I narrowed it down to the Spoon plugin. When deactivated, it doesn't happen.

![Schermafbeelding 2019-04-03 om 14 19 03](https://user-images.githubusercontent.com/6794819/55478409-f79edc80-561b-11e9-95b2-fcebad7582e3.png)

What do you need from me to help you solve this issue?

**Comment by joshangell** [comment]
Interesting ... is this just an upgrade to the latest version of Craft?

**Comment by nilsenpaul** [comment]
> Interesting ... is this just an upgrade to the latest version of Craft?

It's an update to the latest version of Craft (3.1.20.1) and I've updated some other plugins. Tried to rebuild project config, as that's the answer to a lot of issues, but to no avail :)

**Comment by joshangell** [comment]
Could you send me a current DB backup and `composer.json` file to josh@angell.io please? I’m struggling to reproduce this locally. Thanks!

**Comment by joshangell** [comment]
Hi @nilsenpaul - any chance you could send that DB backup and `composer.json` over?

**Comment by nilsenpaul** [comment]
Sorry Josh, I started dumping the DB when you asked me, and then realised it's full of Commerce customer details that I can't share without getting into trouble. Then I tried to think of a way to solve this without going through too much trouble, got caught up in daily life, and forgot about it :).

I'll try and duplicate the DB with certain tables truncated, will send it to you.

**Comment by pseudoclass** [comment]
Hi @joshangell - I seem to be having the same problem. I'll send over a DB dump and the composer.json file here in a bit

**Comment by joshangell** [comment]
Anyone else seeing this? I can’t reproduce so am closing it for now - if anyone does see it please do re-open and send me a db and composer.json so I can try track it down.
