### ISSUE TITLE
Move Spoon setup stuff into the utilities area

### ISSUE THREAD

**Issue by joshangell** [angell-co/Spoon#60]
Idea from @bossanova808:

> Just a thought...while you are in there looking at this, one little thing - I'd personally prefer to see the Spoon setup stuff moved into the utilities area - to me that left column is for stuff like entries and to give access to things that will change a lot/regularly. Spoon is kinda a static thing, for the most part, once set up.

> Just a thought - might be worth asking in Discord what people thing but my OCD doesn't like plugins appearing in there personally.

![](https://user-images.githubusercontent.com/731309/56624724-6bf9f800-667d-11e9-987f-20bc8c677e80.png)

**Comment by engram-design** [comment]
Definitely a +1 from me

**Comment by bossanova808** [comment]
(I _actually_ think plugins should just, generally, leave their settings in the normal plugin area -> settings spot..rather even than the utilities area...unless they are something to support content editing/entry like SEOmatic, or a real management console or utility type thing).

**Comment by joshangell** [comment]
I think the reason I originally moved it was because it no longer actually saved to the settings row in the plugins table, which is now not applicable anyway. I think I’ll aim to get it back to being only linked to from the settings page first of all, failing that utilities it is.

The other issue is that at some point I will probably need sub pages, so then utilities may not work that well.

**Comment by joshangell** [comment]
But I concur that currently the main nav is a bit overkill given there is no content management happening!
