### ISSUE TITLE
Issue with Super Table support, on Craft 3.1.34

### ISSUE THREAD

**Issue by blackstalk** [angell-co/Spoon#64]
I just updated to Craft 3.1.34 and am now getting this error:

Argument 1 passed to verbb\supertable\services\SuperTableService::getBlockTypeById() must be of the type integer, null given, called in .../vendor/angellco/spoon/src/services/BlockTypes.php on line 440

Currently on Spoon 3.3.7

**Comment by joshangell** [comment]
@blackstalk are you still seeing this issue at all? I can’t reproduce it myself so am closing for now, will reopen it if you are still seeing it - if so please do send me a db dump and `composer.json` file to josh@angell.io
