### ISSUE TITLE
Causing issues with expanded/collapsed state

### ISSUE THREAD

**Issue by engram-design** [angell-co/Spoon#67]
Refer to https://d.pr/i/Kzhc0a where there are some layout issues with the expanded/collapsed states using Spoon.

The actual issue seems tricky to pin-point, and is often show on next/previous blocks when toggling this state. Resizing the window makes the layout issue go away, which makes me think its a JS reflow issue, or something similar.

**Comment by joshangell** [comment]
Hmmm OK - I’ve had a look at this one, but can’t reproduce it as yet. What browser are you testing in?

Also roughly how many block-types and blocks do you have on the page?

**Comment by jsunsawyer** [comment]
Also experiencing this, but my issue isn't fixed from a window resize.

For my specific setup, it seems that only tabs that have a single entry field causes strange collapsing. Also, whenever a block uses tabbed content for its fields, and the next block doesn't, the blocks don't collapse correctly.

![Screen Shot 2019-11-25 at 9 45 24 AM](https://user-images.githubusercontent.com/1007191/69564711-5c6ec480-0f68-11ea-9505-4b872a3fa543.png)

Another importing thing to note from this screenshot is that the collapsed view loses the text that helps the user know which item is collapsed.

**Comment by joshangell** [comment]
Ah thanks for this @jsunsawyer, very helpful. Hopefully I’ll be able to reproduce this now!

**Comment by joshangell** [comment]
Boom! I can finally reproduce it after all this time 😂

![image](https://user-images.githubusercontent.com/404219/70135276-a864ec00-1681-11ea-85eb-5f6bec9481dd.png)

**Comment by joshangell** [comment]
@jsunsawyer @engram-design OK chaps - this should do it, will be released shortly.
