### ISSUE TITLE
Breaks SuperTable in Matrix View

### ISSUE THREAD

**Issue by theskyfloor** [angell-co/Spoon#7]
If I use a Matrix within a Matrix and SuperTable is set to Matrix layout no blocks or content shows up.

Enabled:

<img width="977" alt="screen shot 2018-07-10 at 7 51 49 am" src="https://user-images.githubusercontent.com/8887839/42511030-6566eb32-8416-11e8-907a-f9cc9477b3e2.png">

Disabled:

<img width="813" alt="screen shot 2018-07-10 at 7 51 26 am" src="https://user-images.githubusercontent.com/8887839/42511040-6b657404-8416-11e8-9277-737e51cdeb5f.png">

**Comment by theskyfloor** [comment]
I should add that Spoon works correctly when the SuperTable field is set to Table or Row layout

**Comment by theskyfloor** [comment]
Actually, that isn't entirely true. Fields initialize correctly when I create a new block/row but when I save and refresh they no longer appear (at least for my plain text field test):

<img width="371" alt="screen shot 2018-07-10 at 7 57 17 am" src="https://user-images.githubusercontent.com/8887839/42511242-e8b62bce-8416-11e8-88e8-fb412ff15276.png">

**Comment by joshangell** [comment]
Aaah yes, is this basically the same issue? https://github.com/angell-co/Pimp-My-Matrix/issues/40

**Comment by theskyfloor** [comment]
Looks similar!

**Comment by joshangell** [comment]
Cool, I’ve added it to the roadmap :)

**Comment by joshangell** [comment]
Update: this is partially fixed in that you can now see the fields, but the buttons and settings menus are pretty broken.

**Comment by joshangell** [comment]
Added support for Super Table allowing you to use Spoon on Matrix fields that are inside Super Table fields, both `Super Table > Matrix` and `Matrix > Super Table > Matrix`.

Initially this is only for the global context which means you can only change these nested Matrix fields in the Spoon settings page and those changes apply everywhere.

See #19 for updates on that.
