### ISSUE TITLE
Error when running on a PHP version that is less than 7.1.0

### ISSUE THREAD

**Issue by G17creative** [angell-co/Spoon#72]
Error: Could not delete /var/www/clients/client1/web393/web/vendor/angellco/spoon/composer.json: unlink(/var/www/clients/client1/web393/web/vendor/angellco/spoon/composer.json): Permission denied

Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Package "danielstjules/stringy" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
Package operations: 0 installs, 1 update, 0 removals
- Updating angellco/spoon (3.3.7 => 3.4.0):

**Comment by G17creative** [comment]
After updating the vendor folder permissions and running the update again we're getting a new error:

Status: Internal Server Error

Response: <pre>Exception &#039;ParseError&#039; with message &#039;syntax error, unexpected &#039;?&#039;&#039;

in /var/www/clients/client1/web393/web/vendor/angellco/spoon/src/services/BlockTypes.php:70

Stack trace:
#0 /var/www/clients/client1/web393/web/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile(&#039;/var/www/client...&#039;)
#1 [internal function]: Composer\Autoload\ClassLoader-&gt;loadClass(&#039;angellco\\spoon\\...&#039;)
#2 [internal function]: spl_autoload_call(&#039;angellco\\spoon\\...&#039;)
#3 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/di/Container.php(447): ReflectionClass-&gt;__construct(&#039;angellco\\spoon\\...&#039;)
#4 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/di/Container.php(374): yii\di\Container-&gt;getDependencies(&#039;angellco\\spoon\\...&#039;)
#5 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container-&gt;build(&#039;angellco\\spoon\\...&#039;, Array, Array)
#6 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container-&gt;get(&#039;angellco\\spoon\\...&#039;, Array)
#7 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(&#039;angellco\\spoon\\...&#039;)
#8 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/base/Module.php(745): yii\di\ServiceLocator-&gt;get(&#039;blockTypes&#039;, false)
#9 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\base\Module-&gt;get(&#039;blockTypes&#039;)
#10 /var/www/clients/client1/web393/web/vendor/angellco/spoon/src/Spoon.php(103): yii\di\ServiceLocator-&gt;__get(&#039;blockTypes&#039;)
#11 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/base/BaseObject.php(109): angellco\spoon\Spoon-&gt;init()
#12 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject-&gt;__construct(Array)
#13 /var/www/clients/client1/web393/web/vendor/craftcms/cms/src/base/Plugin.php(130): yii\base\Module-&gt;__construct(&#039;spoon&#039;, Object(craft\web\Application), Array)
#14 [internal function]: craft\base\Plugin-&gt;__construct(&#039;spoon&#039;, Object(craft\web\Application), Array)
#15 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass-&gt;newInstanceArgs(Array)
#16 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container-&gt;build(&#039;angellco\\spoon\\...&#039;, Array, Array)
#17 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container-&gt;get(&#039;angellco\\spoon\\...&#039;, Array, Array)
#18 /var/www/clients/client1/web393/web/vendor/craftcms/cms/src/services/Plugins.php(897): yii\BaseYii::createObject(Array, Array)
#19 /var/www/clients/client1/web393/web/vendor/craftcms/cms/src/services/Plugins.php(230): craft\services\Plugins-&gt;createPlugin(&#039;spoon&#039;, Array)
#20 /var/www/clients/client1/web393/web/vendor/craftcms/cms/src/base/ApplicationTrait.php(1375): craft\services\Plugins-&gt;loadPlugins()
#21 /var/www/clients/client1/web393/web/vendor/craftcms/cms/src/web/Application.php(112): craft\web\Application-&gt;_postInit()
#22 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application-&gt;init()
#23 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject-&gt;__construct(Array)
#24 /var/www/clients/client1/web393/web/vendor/craftcms/cms/src/web/Application.php(100): yii\base\Application-&gt;__construct(Array)
#25 [internal function]: craft\web\Application-&gt;__construct(Array)
#26 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass-&gt;newInstanceArgs(Array)
#27 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container-&gt;build(&#039;craft\\web\\Appli...&#039;, Array, Array)
#28 /var/www/clients/client1/web393/web/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container-&gt;get(&#039;craft\\web\\Appli...&#039;, Array, Array)
#29 /var/www/clients/client1/web393/web/vendor/craftcms/cms/bootstrap/bootstrap.php(244): yii\BaseYii::createObject(Array)
#30 /var/www/clients/client1/web393/web/vendor/craftcms/cms/bootstrap/web.php(52): require(&#039;/var/www/client...&#039;)
#31 /var/www/clients/client1/web393/web/index.php(23): require(&#039;/var/www/client...&#039;)
#32 {main}</pre>

**Comment by joshangell** [comment]
Hi @G17creative - I’m guessing you’re running a version of PHP lower than 7.1.0? Is that correct?

**Comment by G17creative** [comment]
Hi @joshangell, thanks for getting back. That's correct, it's just 7.0.33

**Comment by joshangell** [comment]
Aha OK then - you will need to be on at least PHP 7.1.0, see here for reasons why: https://www.php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration

I will leave this open for now until I force that requirement in the README and with composer.
