### ISSUE TITLE
Issue with Solspace Calendar on Craft 3.3.16.3

### ISSUE THREAD

**Issue by rmdiaconu** [angell-co/Spoon#73]
After updating to Craft 3.3.16.3 editing Events or adding new ones with Solspace Calendar is not possible anymore due to the following error:

[Screenshot](https://www.dropbox.com/s/hujgdrtwuipvv81/Screenshot%202019-12-02%2011.55.35.png?dl=0)

However, after disabling Spoon, Solspace Calendar works just fine.

**Application Info**

PHP version - 7.2.21
OS version - Darwin 19.0.0
Database driver & version - MySQL 5.7.26
Image driver & version - Imagick 3.4.3 (ImageMagick 6.9.6-2)
Craft edition & version - Craft Pro 3.3.16.3
Yii version - 2.0.30
Twig version - 2.12.2
Guzzle version - 6.4.1
Imagine version - 1.2.3-dev

**Plugins**

Calendar- 2.0.25
Cookies - 1.1.11
Field Manager - 2.1.1
Freeform - 3.5.4
Imager - v2.3.0
Linkit - 1.1.11
Navigation - 1.1.14.1
Neo - 2.5.8
No-Cache - 2.0.6
Redactor - 2.4.0
Retour - 3.1.29
SEOmatic - 3.2.35
Spoon - 3.4.0
Sprout Encode Email - 2.0.7
Tags - 1.0.5
Template Select - 2.0.2
Video Embedder - 1.1.4
Wordsmith - 3.1.1
XML Sitemap - 1.2.0

**Comment by joshangell** [comment]
Thanks for this @rmdiaconu, I’ll have a look see whats going on today.
