### ISSUE TITLE
Spoon 3.4.1 migration failure 

### ISSUE THREAD

**Issue by lukebailey** [angell-co/Spoon#76]
When upgrading to Spoon 3.4.1 from 3.3.7 we are seeing the following error when deploying to environments with `allowAdminChanges` disabled 

![image](https://user-images.githubusercontent.com/3185073/70329380-3207eb80-1833-11ea-9133-87ae559ae396.png)

**Comment by lukebailey** [comment]
Turns out if you actually commit the project.yaml file thigns work as expected...

**Comment by joshangell** [comment]
Phew! Thanks for letting me know :)
