### ISSUE TITLE
Project config doesn't match DB

### ISSUE THREAD

**Issue by justinvandenberg** [angell-co/Spoon#77]
I updated from `3.3.6` to `3.4.2` and `context` in the project config doesn't match `context` in the `craft_spoon_blocktypes` table. The project config is similar to `entrytype:151dbc70-ed67-44d1-926b-01d229f8b256` while the DB is more like `entrytype:5`. I've tried to manually sync and run migrations.

**Comment by joshangell** [comment]
Hmm OK, can you see the following migration row in your `craft_migrations` table?

`m191122_115434_UpgradeToSupportProjectConfig`

If it is, then I would try removing that row and then running the migration from the cli like so:

`./craft migrate/up --plugin spoon`

Let me know how you get on!

**Comment by joshangell** [comment]
@justinvandenberg how did you get on?

**Comment by justinvandenberg** [comment]
I was able to get it working. I rolled back to a previous version and matched the other environment in the CP.

**Comment by joshangell** [comment]
Thanks for the update - I’ll close this for now, hopefully it was a one off.
