### ISSUE TITLE
Blocks getting reassigned to the wrong groups

### ISSUE THREAD

**Issue by elivz** [angell-co/Spoon#80]
I am seeing an issue, where I haven't been able to really track down exactly what is going on. But I am hoping maybe other people are seeing the same thing. 

In my local dev environment, I have all the blocks in a "content builder" Matrix field assigned to several groups. Works great! However, just recently (I believe since the Spoon update that moved the group configuration into `project.yaml`), when I deploy to our staging or production servers, all of the blocks are randomly moved to different groups. I tried manually resetting them all to the correct groups on the staging server, but when I next deployed and synced the `project.yaml` changes, they were all back to the wrong places again. Any idea what could be going on? I guess I can just downgrade back to 3.3.7 and keep the grouping config in the DB, but that doesn't seem like a long-term solution....

**Comment by bentilden** [comment]
I'm having the same problem, plus within a group, the order of blocks is randomly changed every time I deploy.

**Comment by jamielaughton** [comment]
I have the same issue, its driving me nuts as i have a huge content builder which I'm trying to maintain for several users and stuff keeps moving around. A fix for this would be great!

**Comment by joshangell** [comment]
I’ll be working on this just as soon as I’ve ticked off #79

**Comment by joshangell** [comment]
Please see this comment for how to road test the current fix: https://github.com/angell-co/Spoon/issues/79#issuecomment-581993328

Any help testing would be much appreciated!
