### ISSUE TITLE
Newly added matrix blocks not appearing in Spoon layout

### ISSUE THREAD

**Issue by michelstomp** [angell-co/Spoon#81]
I have quite a large matrix field, with some 12 blocks. All blocks have been assigned to grouped layout in Spoon and field layouts for individual groups are made. 

Now I've added a new block to the matrix field. The new block does not appear in Spoon. And as a result of this, the new block is also not available in the entry_type form. 

Anyone have any ideas on this?

**Comment by joshangell** [comment]
Hey - this might be a UX thing with the plugin from what I can work out, are you saying that you have a grouped setup already for a Matrix field, then you go add a new block and expect it to appear in the groups? If so, every time you add new blocks to the Matrix field you have to go and add them to the groups you want them in as well - it doesn’t pick up new blocks without doing that.
