### ISSUE TITLE
Craft's info table being updated on every page request

### ISSUE THREAD

**Issue by johndwells** [angell-co/Spoon#82]
Hi,

I've noticed that on every Craft request (front-end or back-end requests at least), there is an UPDATE being applied to the craft `info` table. The only value that is changing every time is the column `fieldVersion`. I've tracked this down to Spoon (disabled Spoon == no more updates).

I've tried to see if I could track down when/why this was happening, but it wasn't immediately obvious, sorry.

Craft 3.3.20.1
Spoon 3.4.3

Let me know if you'd like a project yaml file or any other info that you might find useful.

**Comment by joshangell** [comment]
Hi John - thanks for this and all the details, I will aim to look at this next week sometime if possible. Thanks for your patience!

**Comment by johndwells** [comment]
👍

**Comment by joshangell** [comment]
OK - fix incoming in the tonights release - it was a bit of a hack dropped in to fix someone else’s edge-case, turns out it wasn’t a good idea!

**Comment by johndwells** [comment]
:clap: Gotta love those "fixes"... Thanks Josh! :)
