### ISSUE TITLE
craft_spoon_blocktypes persists after plugin is removed

### ISSUE THREAD

**Issue by circa1977** [angell-co/Spoon#85]
I removed the plugin and the database table is still intact.

**Comment by circa1977** [comment]
After uninstalling this, it's still referenced in project config, which is preventing me from pushing to my server. Frustrating.

**Comment by joshangell** [comment]
Is the plugin still referenced in the plugins key? Or is it just the `spoonBlockTypes` that’s still present?

**Comment by circa1977** [comment]
The plugin was still referenced. I had to do project-config/rebuild to clean it up.

**Comment by joshangell** [comment]
OK that’s interesting, I don’t think plugins have control over that ... we can remove database tables etc but the plugins key is controller by Craft.

Still, I’ll look into it when I address the original part of this issue this week.

**Comment by joshangell** [comment]
Right, after some digging I can’t see the specific issues you were facing, the table is dropped from the DB for me as is the spoon part of the plugins key in project config.

However the other spoon data was still left in project config, so I have also removed that on uninstall.
