### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by lindseydiloreto** [angell-co/Spoon#86]
I just installed Spoon on a brand new Craft install, and it immediately kicked up this error...

<img width="716" alt="Ω 2020-02-05 at 1 02 49 PM" src="https://user-images.githubusercontent.com/5309692/73883119-33946680-4818-11ea-8861-e0092a9de0ae.png">

In fact, the entire site is now locked down with this error. Fortunately, I just spun this site up from scratch 10 minutes ago!

Craft: 3.4.3
Spoon: 3.5.0

**Comment by joshangell** [comment]
Argh! Thanks for that Lindesy - clearly didn’t add these fields to the install migration ....

**Comment by lindseydiloreto** [comment]
Lol, whoops. At least I discovered it on a burner site! 👍

**Comment by joshangell** [comment]
I’m very grateful! Fix incoming shortly ...

**Comment by joshangell** [comment]
@lindseydiloreto try that!

**Comment by lindseydiloreto** [comment]
That totally fixed it!! Thanks @joshangell! 🍺
