### ISSUE TITLE
Updating Spoon to 3.5.2 deletes almost all Craft CMS fields

### ISSUE THREAD

**Issue by chasegiunta** [angell-co/Spoon#96]
I'm just putting this on your radar, but since we've decided to move onto another Matrix solution I won't really be able to troubleshoot with you. I'm just mentioning it as a courtesy but feel free to close.

After updating a site from Craft 3.3.19 to Craft 3.4.24 successfully, the very first update we tried to run was Spoon (3.4.3 to 3.5.2), but doing so actually removed all but like 6 Craft CMS fields (out of 100+) within the install. I have to assume this might be a project.yaml getting borked along the update but I have no idea. I was able to recreate this twice.

The only way I was able to update both Craft and Spoon successfully was to uninstall Spoon, then update Craft, and then reinstall Spoon, but doing so of course removed all Spoon configuration.

**Comment by joshangell** [comment]
Good Lord, thanks for letting me know. This is highly likely project config related, and issues abound with that. Its particularly weird as Spoon doesn’t actually touch the fields key in project config at all, it has its own key that it works within so I have no idea how this happened.

I will see if I can reproduce it my end, but frankly at the moment reproducing most of the bugs that come in is proving impossible!

Again thanks for letting me know Chase and I’ll see what happens.

**Comment by joshangell** [comment]
OK I have no idea how this happened and can’t reproduce it so am closing for now.

**Comment by joshangell** [comment]
Actually having said that I think it might be a similar issue to #91 so I’m going to consolidate there.
