### ISSUE TITLE
"Right-hand side of 'instanceof' is not an object error" when updating to Craft 3.4.30

### ISSUE THREAD

**Issue by howells** [angell-co/Spoon#98]
When I updated to Craft 3.4.30, none of my Matrix fields were visible, with the following error shown in Console:

```
jquery.js:4055 Uncaught TypeError: Right-hand side of 'instanceof' is not an object
    at s.constructor.trigger (garnish.js:838)
    at s.constructor.destroy (garnish.js:920)
    at s.constructor.destroy (garnish.js:3753)
    at s.constructor.e [as destroy] (garnish.js:79)
    at s.constructor.init (garnish.js:3539)
    at s.constructor.constructor (garnish.js:768)
    at s.constructor (garnish.js:40)
    at new s.constructor (garnish.js:40)
    at s.constructor.init (MatrixInput.js:440)
    at s.constructor.constructor (garnish.js:768)
```

When I disabled Spoon (version 3.5.2), the fields were visible again.

**Comment by joshangell** [comment]
Hey @howells thanks for this, I’m due to sit down and debug some stuff on this today so I’ll take a look shortly.

**Comment by tigerchick** [comment]
I just got the same issue.

**Comment by joshangell** [comment]
Definitely fixed in the next release @tigerchick - its down to recent Super Table changes.

**Comment by tigerchick** [comment]
> Definitely fixed in the next release @tigerchick - its down to recent Super Table changes.

Thank you so much for looking into this so quickly Josh. 
I hate to be "that guy", but any idea when that might be? Was meant to be getting something out today but I can probably revert to the previous Craft version if you need a bit of time.

**Comment by joshangell** [comment]
will be releasing today - maybe around 7:30pm UK time if I can’t do it in the next ten mins lol

**Comment by joshangell** [comment]
You can always update your `composer.json` to use `dev-develop` instead of the version constraint.

**Comment by tigerchick** [comment]
Awesome! :)

**Comment by tigerchick** [comment]
> @tigerchick there you go - give that a whirl!

Superb! You've nailed it. Thank you :)

**Comment by davidhellmann** [comment]
@joshangell 
Looks like I've a similar Problem
Spoon: 3.5.3
Craft: 3.4.30

It looks like this:
![image](https://user-images.githubusercontent.com/764292/90507564-6075ee80-e156-11ea-874a-904681b4beb4.png)

When I close the Blocks it looks like this: 
![image](https://user-images.githubusercontent.com/764292/90507599-71befb00-e156-11ea-823f-c31a9169301b.png)

When I reopen the Blocks all is fine:
![image](https://user-images.githubusercontent.com/764292/90507632-7f748080-e156-11ea-8bb6-b1a9a2a413b0.png)


After reloading all is hidden again.
